networks:
  prod:

services:
  db:
    image: mysql:9.3
    environment: 
      - MYSQL_ROOT_PASSWORD=${PASSW}
      - MYSQL_DATABASE=${NAME}
    ports:
      - '3306:3306'
    healthcheck:
      test: mysql --user=${USER} --password=${PASSW} --execute="SHOW DATABASES;"
      interval: 10s
      timeout: 60s
      retries: 5
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - prod


  phpmyadmin:
    image: phpmyadmin:latest
    depends_on:
      - db
    restart: always
    ports:
      - 8080:8080
    env_file:
      - .env
    networks:
      - prod

  backend:
      image: foodshop_backend
      ports:
      - '8000:8000'
      build: 
        context: ./
      volumes:
      - ./backend/:/backend/ 
      depends_on:
        db:
          condition: service_healthy
      networks:
        - prod

  frontend:
    build:
      context: ./frontend
    image: foodshop_frontend
    ports:
      - "5173:5173"
    volumes:
      - ./template:/etc/nginx/templates/
    environment:
      NGINX_ENVSUBST_OUTPUT_DIR: /etc/nginx/sites-enabled
    depends_on:
      - backend
    networks:
      - prod


  nginx:
    image: nginx:stable-alpine
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
    networks:
      - prod


volumes: 
  db-data:


